sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc
 - dmd
 - ldc-beta
 - ldc-1.17.0
 - ldc-1.15.0
 - ldc-1.8.0
 - dmd-2.085.1
script:
 - dub --root=example --compiler=${DC}
 - dub test --compiler=${DC} --config=ulong_length
 - dub test --compiler=${DC} --build=unittest-cov
after_success:
 - bash <(curl -s https://codecov.io/bash)
