sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc
 - dmd
 - ldc-1.24.0
 - ldc-1.23.0
 - ldc-1.22.0
 - ldc-1.17.0
 - ldc-1.15.0
script:
 - dub --root=example --compiler=${DC} --single mir_algebraic_example.d
 - dub --root=example --compiler=${DC} --single taggedalgebraic_example.d
 - dub test --compiler=${DC}
 - dub test --compiler=${DC} --build=unittest-cov
after_success:
 - bash <(curl -s https://codecov.io/bash)
