name: base
on: [push]

jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        dc: 
          - dmd-latest
          - ldc-latest

          - dmd-2.095.1
          - dmd-2.094.2

          - ldc-1.25.0
          - ldc-1.24.0

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
            compiler: ${{ matrix.dc }}

      - name: Run tests
        run: |
          dub test
          dub --root=example --single mir_algebraic_example.d
          dub --root=example --single taggedalgebraic_example.d
          dub --root=example --single sumtype_example.d
          dub --root=example --single all_example.d
