name: base
on: [push]

jobs:
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        dc: 
          - dmd-latest
          - ldc-latest

          - dmd-2.098.1
          - dmd-2.102.2
          - dmd-2.106.1

          - ldc-1.28.1
          - ldc-1.32.1
          - ldc-1.36.0
        exclude:
          # linker error "section __DATA/__thread_bss has type zero-fill but non-zero file offset"
          - os: macOS-latest
            dc: dmd-2.098.1

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
            compiler: ${{ matrix.dc }}

      - name: Run tests
        run: |
          dub test
          dub test --config=allow-raw-unions
          dub --root=example --single mir_algebraic_example.d
          dub --root=example --single taggedalgebraic_example.d
          dub --root=example --single sumtype_example.d
          dub --root=example --single all_example.d
